# Generated by Django 6.1 on 2026-08-17 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_currency_product_email_product_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['created_at']},
        ),
    ]
